on:
    push:
        branches: main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'

            - name: Install Vercel CLI
              run: npm install --global vercel@latest

            - name: Install Dependencies
              run: composer install --no-dev --prefer-dist --no-interaction --no-progress

              env:
                APP_ENV: production
                DB_CONNECTION: pgsql
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: 5432
                DB_DATABASE: ${{ secrets.DB_DATABASE }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

            - name: Generate .env File
              run: |
                echo "APP_ENV=production" >> .env
                echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
                echo "DB_CONNECTION=pgsql" >> .env
                echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
                echo "DB_PORT=5432" >> .env
                echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
                echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
                echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env


            - name: Deploy to Vercel
              run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
              env:
                VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
